//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.08 at 06:10:07 PM CDT 
//


package com.ejp.golf.league.legacy.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CourseId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="NineName" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="50"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="HoleNo" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/&gt;
 *         &lt;element name="Hdcp" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/&gt;
 *         &lt;element name="Par" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/&gt;
 *         &lt;element name="Yardage" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "courseId",
    "nineName",
    "holeNo",
    "hdcp",
    "par",
    "yardage"
})
@XmlRootElement(name = "Holes")
public class Holes {

    @XmlElement(name = "CourseId")
    protected Integer courseId;
    @XmlElement(name = "NineName")
    protected String nineName;
    @XmlElement(name = "HoleNo")
    protected Short holeNo;
    @XmlElement(name = "Hdcp")
    protected Short hdcp;
    @XmlElement(name = "Par")
    protected Short par;
    @XmlElement(name = "Yardage")
    protected Integer yardage;

    /**
     * Gets the value of the courseId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * Sets the value of the courseId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCourseId(Integer value) {
        this.courseId = value;
    }

    /**
     * Gets the value of the nineName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNineName() {
        return nineName;
    }

    /**
     * Sets the value of the nineName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNineName(String value) {
        this.nineName = value;
    }

    /**
     * Gets the value of the holeNo property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getHoleNo() {
        return holeNo;
    }

    /**
     * Sets the value of the holeNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setHoleNo(Short value) {
        this.holeNo = value;
    }

    /**
     * Gets the value of the hdcp property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getHdcp() {
        return hdcp;
    }

    /**
     * Sets the value of the hdcp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setHdcp(Short value) {
        this.hdcp = value;
    }

    /**
     * Gets the value of the par property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getPar() {
        return par;
    }

    /**
     * Sets the value of the par property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setPar(Short value) {
        this.par = value;
    }

    /**
     * Gets the value of the yardage property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getYardage() {
        return yardage;
    }

    /**
     * Sets the value of the yardage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setYardage(Integer value) {
        this.yardage = value;
    }

}
