//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.05 at 02:28:26 PM CDT 
//


package com.ejp.golf.league.legacy.domain;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ejp.golf.league.legacy.domain package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ejp.golf.league.legacy.domain
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CoursesList }
     * 
     */
    public CoursesList createCoursesList() {
        return new CoursesList();
    }

    /**
     * Create an instance of {@link Courses }
     * 
     */
    public Courses createCourses() {
        return new Courses();
    }

    /**
     * Create an instance of {@link FlightsList }
     * 
     */
    public FlightsList createFlightsList() {
        return new FlightsList();
    }

    /**
     * Create an instance of {@link Flights }
     * 
     */
    public Flights createFlights() {
        return new Flights();
    }

    /**
     * Create an instance of {@link HolesList }
     * 
     */
    public HolesList createHolesList() {
        return new HolesList();
    }

    /**
     * Create an instance of {@link Holes }
     * 
     */
    public Holes createHoles() {
        return new Holes();
    }

    /**
     * Create an instance of {@link NinesList }
     * 
     */
    public NinesList createNinesList() {
        return new NinesList();
    }

    /**
     * Create an instance of {@link Nines }
     * 
     */
    public Nines createNines() {
        return new Nines();
    }

    /**
     * Create an instance of {@link PlayerSumList }
     * 
     */
    public PlayerSumList createPlayerSumList() {
        return new PlayerSumList();
    }

    /**
     * Create an instance of {@link PlayerSum }
     * 
     */
    public PlayerSum createPlayerSum() {
        return new PlayerSum();
    }

    /**
     * Create an instance of {@link PlayerTranList }
     * 
     */
    public PlayerTranList createPlayerTranList() {
        return new PlayerTranList();
    }

    /**
     * Create an instance of {@link PlayerTran }
     * 
     */
    public PlayerTran createPlayerTran() {
        return new PlayerTran();
    }

    /**
     * Create an instance of {@link PlayersList }
     * 
     */
    public PlayersList createPlayersList() {
        return new PlayersList();
    }

    /**
     * Create an instance of {@link Players }
     * 
     */
    public Players createPlayers() {
        return new Players();
    }

    /**
     * Create an instance of {@link ScheduleList }
     * 
     */
    public ScheduleList createScheduleList() {
        return new ScheduleList();
    }

    /**
     * Create an instance of {@link Schedule }
     * 
     */
    public Schedule createSchedule() {
        return new Schedule();
    }

    /**
     * Create an instance of {@link ScheduleMasterList }
     * 
     */
    public ScheduleMasterList createScheduleMasterList() {
        return new ScheduleMasterList();
    }

    /**
     * Create an instance of {@link ScheduleMaster }
     * 
     */
    public ScheduleMaster createScheduleMaster() {
        return new ScheduleMaster();
    }

    /**
     * Create an instance of {@link ScoreCardList }
     * 
     */
    public ScoreCardList createScoreCardList() {
        return new ScoreCardList();
    }

    /**
     * Create an instance of {@link ScoreCard }
     * 
     */
    public ScoreCard createScoreCard() {
        return new ScoreCard();
    }

    /**
     * Create an instance of {@link TeamSumList }
     * 
     */
    public TeamSumList createTeamSumList() {
        return new TeamSumList();
    }

    /**
     * Create an instance of {@link TeamSum }
     * 
     */
    public TeamSum createTeamSum() {
        return new TeamSum();
    }

    /**
     * Create an instance of {@link TeesList }
     * 
     */
    public TeesList createTeesList() {
        return new TeesList();
    }

    /**
     * Create an instance of {@link Tees }
     * 
     */
    public Tees createTees() {
        return new Tees();
    }

    /**
     * Create an instance of {@link WeekDatesList }
     * 
     */
    public WeekDatesList createWeekDatesList() {
        return new WeekDatesList();
    }

    /**
     * Create an instance of {@link WeekDates }
     * 
     */
    public WeekDates createWeekDates() {
        return new WeekDates();
    }

}
