//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.04 at 07:11:09 PM CDT 
//


package com.ejp.golf.league.legacy.domain;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ejp.golf.league.legacy.domain package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ejp.golf.league.legacy.domain
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FlightsRoot }
     * 
     */
    public FlightsRoot createFlightsRoot() {
        return new FlightsRoot();
    }

    /**
     * Create an instance of {@link Flights }
     * 
     */
    public Flights createFlights() {
        return new Flights();
    }

    /**
     * Create an instance of {@link PlayerTranRoot }
     * 
     */
    public PlayerTranRoot createPlayerTranRoot() {
        return new PlayerTranRoot();
    }

    /**
     * Create an instance of {@link PlayerTran }
     * 
     */
    public PlayerTran createPlayerTran() {
        return new PlayerTran();
    }

    /**
     * Create an instance of {@link PlayersRoot }
     * 
     */
    public PlayersRoot createPlayersRoot() {
        return new PlayersRoot();
    }

    /**
     * Create an instance of {@link Players }
     * 
     */
    public Players createPlayers() {
        return new Players();
    }

}
