//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.09 at 12:25:24 PM CDT 
//


package com.ejp.golf.league.legacy.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Golfer" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="GameDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="Ctr" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Hdcp" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" minOccurs="0"/&gt;
 *         &lt;element name="H1" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="H2" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="H3" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="H4" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="H5" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="H6" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="H7" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="H8" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="H9" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="GrossScore" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="NetScore" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="N1" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="N2" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="N3" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="N4" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="N5" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="N6" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="N7" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="N8" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="N9" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="Flight" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="Team" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="Status" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="1"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CardNumber" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="Counter" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="NetPoints" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="MatchPoints" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="TeamNet" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&gt;
 *         &lt;element name="Week" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="Back9" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="Par1" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="Par2" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="Par3" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="Par4" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="Par5" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="Par6" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="Par7" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="Par8" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="Par9" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="Remove" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="Tees" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="50"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="DatePlayed" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="CourseId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "golfer",
    "gameDate",
    "ctr",
    "hdcp",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "h7",
    "h8",
    "h9",
    "grossScore",
    "netScore",
    "n1",
    "n2",
    "n3",
    "n4",
    "n5",
    "n6",
    "n7",
    "n8",
    "n9",
    "flight",
    "team",
    "status",
    "cardNumber",
    "counter",
    "netPoints",
    "matchPoints",
    "teamNet",
    "week",
    "back9",
    "par1",
    "par2",
    "par3",
    "par4",
    "par5",
    "par6",
    "par7",
    "par8",
    "par9",
    "remove",
    "tees",
    "datePlayed",
    "courseId"
})
@XmlRootElement(name = "PlayerTran")
public class PlayerTran {

    @XmlElement(name = "Golfer")
    protected Integer golfer;
    @XmlElement(name = "GameDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar gameDate;
    @XmlElement(name = "Ctr")
    protected int ctr;
    @XmlElement(name = "Hdcp")
    @XmlSchemaType(name = "unsignedByte")
    protected Short hdcp;
    @XmlElement(name = "H1")
    protected Integer h1;
    @XmlElement(name = "H2")
    protected Integer h2;
    @XmlElement(name = "H3")
    protected Integer h3;
    @XmlElement(name = "H4")
    protected Integer h4;
    @XmlElement(name = "H5")
    protected Integer h5;
    @XmlElement(name = "H6")
    protected Integer h6;
    @XmlElement(name = "H7")
    protected Integer h7;
    @XmlElement(name = "H8")
    protected Integer h8;
    @XmlElement(name = "H9")
    protected Integer h9;
    @XmlElement(name = "GrossScore")
    protected Integer grossScore;
    @XmlElement(name = "NetScore")
    protected Integer netScore;
    @XmlElement(name = "N1")
    protected Integer n1;
    @XmlElement(name = "N2")
    protected Integer n2;
    @XmlElement(name = "N3")
    protected Integer n3;
    @XmlElement(name = "N4")
    protected Integer n4;
    @XmlElement(name = "N5")
    protected Integer n5;
    @XmlElement(name = "N6")
    protected Integer n6;
    @XmlElement(name = "N7")
    protected Integer n7;
    @XmlElement(name = "N8")
    protected Integer n8;
    @XmlElement(name = "N9")
    protected Integer n9;
    @XmlElement(name = "Flight")
    protected Integer flight;
    @XmlElement(name = "Team")
    protected Integer team;
    @XmlElement(name = "Status")
    protected String status;
    @XmlElement(name = "CardNumber")
    protected Integer cardNumber;
    @XmlElement(name = "Counter")
    protected Integer counter;
    @XmlElement(name = "NetPoints")
    protected Integer netPoints;
    @XmlElement(name = "MatchPoints")
    protected Integer matchPoints;
    @XmlElement(name = "TeamNet")
    protected Float teamNet;
    @XmlElement(name = "Week")
    protected Integer week;
    @XmlElement(name = "Back9")
    protected boolean back9;
    @XmlElement(name = "Par1")
    protected Integer par1;
    @XmlElement(name = "Par2")
    protected Integer par2;
    @XmlElement(name = "Par3")
    protected Integer par3;
    @XmlElement(name = "Par4")
    protected Integer par4;
    @XmlElement(name = "Par5")
    protected Integer par5;
    @XmlElement(name = "Par6")
    protected Integer par6;
    @XmlElement(name = "Par7")
    protected Integer par7;
    @XmlElement(name = "Par8")
    protected Integer par8;
    @XmlElement(name = "Par9")
    protected Integer par9;
    @XmlElement(name = "Remove")
    protected boolean remove;
    @XmlElement(name = "Tees")
    protected String tees;
    @XmlElement(name = "DatePlayed")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar datePlayed;
    @XmlElement(name = "CourseId")
    protected Integer courseId;

    /**
     * Gets the value of the golfer property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getGolfer() {
        return golfer;
    }

    /**
     * Sets the value of the golfer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setGolfer(Integer value) {
        this.golfer = value;
    }

    /**
     * Gets the value of the gameDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getGameDate() {
        return gameDate;
    }

    /**
     * Sets the value of the gameDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setGameDate(XMLGregorianCalendar value) {
        this.gameDate = value;
    }

    /**
     * Gets the value of the ctr property.
     * 
     */
    public int getCtr() {
        return ctr;
    }

    /**
     * Sets the value of the ctr property.
     * 
     */
    public void setCtr(int value) {
        this.ctr = value;
    }

    /**
     * Gets the value of the hdcp property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getHdcp() {
        return hdcp;
    }

    /**
     * Sets the value of the hdcp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setHdcp(Short value) {
        this.hdcp = value;
    }

    /**
     * Gets the value of the h1 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getH1() {
        return h1;
    }

    /**
     * Sets the value of the h1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setH1(Integer value) {
        this.h1 = value;
    }

    /**
     * Gets the value of the h2 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getH2() {
        return h2;
    }

    /**
     * Sets the value of the h2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setH2(Integer value) {
        this.h2 = value;
    }

    /**
     * Gets the value of the h3 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getH3() {
        return h3;
    }

    /**
     * Sets the value of the h3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setH3(Integer value) {
        this.h3 = value;
    }

    /**
     * Gets the value of the h4 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getH4() {
        return h4;
    }

    /**
     * Sets the value of the h4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setH4(Integer value) {
        this.h4 = value;
    }

    /**
     * Gets the value of the h5 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getH5() {
        return h5;
    }

    /**
     * Sets the value of the h5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setH5(Integer value) {
        this.h5 = value;
    }

    /**
     * Gets the value of the h6 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getH6() {
        return h6;
    }

    /**
     * Sets the value of the h6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setH6(Integer value) {
        this.h6 = value;
    }

    /**
     * Gets the value of the h7 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getH7() {
        return h7;
    }

    /**
     * Sets the value of the h7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setH7(Integer value) {
        this.h7 = value;
    }

    /**
     * Gets the value of the h8 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getH8() {
        return h8;
    }

    /**
     * Sets the value of the h8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setH8(Integer value) {
        this.h8 = value;
    }

    /**
     * Gets the value of the h9 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getH9() {
        return h9;
    }

    /**
     * Sets the value of the h9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setH9(Integer value) {
        this.h9 = value;
    }

    /**
     * Gets the value of the grossScore property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getGrossScore() {
        return grossScore;
    }

    /**
     * Sets the value of the grossScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setGrossScore(Integer value) {
        this.grossScore = value;
    }

    /**
     * Gets the value of the netScore property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNetScore() {
        return netScore;
    }

    /**
     * Sets the value of the netScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNetScore(Integer value) {
        this.netScore = value;
    }

    /**
     * Gets the value of the n1 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getN1() {
        return n1;
    }

    /**
     * Sets the value of the n1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setN1(Integer value) {
        this.n1 = value;
    }

    /**
     * Gets the value of the n2 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getN2() {
        return n2;
    }

    /**
     * Sets the value of the n2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setN2(Integer value) {
        this.n2 = value;
    }

    /**
     * Gets the value of the n3 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getN3() {
        return n3;
    }

    /**
     * Sets the value of the n3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setN3(Integer value) {
        this.n3 = value;
    }

    /**
     * Gets the value of the n4 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getN4() {
        return n4;
    }

    /**
     * Sets the value of the n4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setN4(Integer value) {
        this.n4 = value;
    }

    /**
     * Gets the value of the n5 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getN5() {
        return n5;
    }

    /**
     * Sets the value of the n5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setN5(Integer value) {
        this.n5 = value;
    }

    /**
     * Gets the value of the n6 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getN6() {
        return n6;
    }

    /**
     * Sets the value of the n6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setN6(Integer value) {
        this.n6 = value;
    }

    /**
     * Gets the value of the n7 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getN7() {
        return n7;
    }

    /**
     * Sets the value of the n7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setN7(Integer value) {
        this.n7 = value;
    }

    /**
     * Gets the value of the n8 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getN8() {
        return n8;
    }

    /**
     * Sets the value of the n8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setN8(Integer value) {
        this.n8 = value;
    }

    /**
     * Gets the value of the n9 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getN9() {
        return n9;
    }

    /**
     * Sets the value of the n9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setN9(Integer value) {
        this.n9 = value;
    }

    /**
     * Gets the value of the flight property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFlight() {
        return flight;
    }

    /**
     * Sets the value of the flight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFlight(Integer value) {
        this.flight = value;
    }

    /**
     * Gets the value of the team property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTeam() {
        return team;
    }

    /**
     * Sets the value of the team property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTeam(Integer value) {
        this.team = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the cardNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCardNumber() {
        return cardNumber;
    }

    /**
     * Sets the value of the cardNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCardNumber(Integer value) {
        this.cardNumber = value;
    }

    /**
     * Gets the value of the counter property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCounter() {
        return counter;
    }

    /**
     * Sets the value of the counter property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCounter(Integer value) {
        this.counter = value;
    }

    /**
     * Gets the value of the netPoints property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNetPoints() {
        return netPoints;
    }

    /**
     * Sets the value of the netPoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNetPoints(Integer value) {
        this.netPoints = value;
    }

    /**
     * Gets the value of the matchPoints property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMatchPoints() {
        return matchPoints;
    }

    /**
     * Sets the value of the matchPoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMatchPoints(Integer value) {
        this.matchPoints = value;
    }

    /**
     * Gets the value of the teamNet property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getTeamNet() {
        return teamNet;
    }

    /**
     * Sets the value of the teamNet property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setTeamNet(Float value) {
        this.teamNet = value;
    }

    /**
     * Gets the value of the week property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getWeek() {
        return week;
    }

    /**
     * Sets the value of the week property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWeek(Integer value) {
        this.week = value;
    }

    /**
     * Gets the value of the back9 property.
     * 
     */
    public boolean isBack9() {
        return back9;
    }

    /**
     * Sets the value of the back9 property.
     * 
     */
    public void setBack9(boolean value) {
        this.back9 = value;
    }

    /**
     * Gets the value of the par1 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPar1() {
        return par1;
    }

    /**
     * Sets the value of the par1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPar1(Integer value) {
        this.par1 = value;
    }

    /**
     * Gets the value of the par2 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPar2() {
        return par2;
    }

    /**
     * Sets the value of the par2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPar2(Integer value) {
        this.par2 = value;
    }

    /**
     * Gets the value of the par3 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPar3() {
        return par3;
    }

    /**
     * Sets the value of the par3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPar3(Integer value) {
        this.par3 = value;
    }

    /**
     * Gets the value of the par4 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPar4() {
        return par4;
    }

    /**
     * Sets the value of the par4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPar4(Integer value) {
        this.par4 = value;
    }

    /**
     * Gets the value of the par5 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPar5() {
        return par5;
    }

    /**
     * Sets the value of the par5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPar5(Integer value) {
        this.par5 = value;
    }

    /**
     * Gets the value of the par6 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPar6() {
        return par6;
    }

    /**
     * Sets the value of the par6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPar6(Integer value) {
        this.par6 = value;
    }

    /**
     * Gets the value of the par7 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPar7() {
        return par7;
    }

    /**
     * Sets the value of the par7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPar7(Integer value) {
        this.par7 = value;
    }

    /**
     * Gets the value of the par8 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPar8() {
        return par8;
    }

    /**
     * Sets the value of the par8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPar8(Integer value) {
        this.par8 = value;
    }

    /**
     * Gets the value of the par9 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPar9() {
        return par9;
    }

    /**
     * Sets the value of the par9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPar9(Integer value) {
        this.par9 = value;
    }

    /**
     * Gets the value of the remove property.
     * 
     */
    public boolean isRemove() {
        return remove;
    }

    /**
     * Sets the value of the remove property.
     * 
     */
    public void setRemove(boolean value) {
        this.remove = value;
    }

    /**
     * Gets the value of the tees property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTees() {
        return tees;
    }

    /**
     * Sets the value of the tees property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTees(String value) {
        this.tees = value;
    }

    /**
     * Gets the value of the datePlayed property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatePlayed() {
        return datePlayed;
    }

    /**
     * Sets the value of the datePlayed property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatePlayed(XMLGregorianCalendar value) {
        this.datePlayed = value;
    }

    /**
     * Gets the value of the courseId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * Sets the value of the courseId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCourseId(Integer value) {
        this.courseId = value;
    }

}
