//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.07 at 02:44:01 PM CDT 
//


package com.ejp.golf.league.legacy.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Ctr" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Golfer" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="Year" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="TotalScores" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="TotalHoles" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="Hdcp" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="GrossEagles" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="GrossBirdies" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="GrossPars" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="GrossBogies" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="GrossOthers" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="NetEagles" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="NetBirdies" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="NetPars" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="NetBogies" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="NetOthers" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="Remove" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ctr",
    "golfer",
    "year",
    "totalScores",
    "totalHoles",
    "hdcp",
    "grossEagles",
    "grossBirdies",
    "grossPars",
    "grossBogies",
    "grossOthers",
    "netEagles",
    "netBirdies",
    "netPars",
    "netBogies",
    "netOthers",
    "remove"
})
@XmlRootElement(name = "PlayerSum")
public class PlayerSum {

    @XmlElement(name = "Ctr")
    protected int ctr;
    @XmlElement(name = "Golfer")
    protected Integer golfer;
    @XmlElement(name = "Year")
    protected Integer year;
    @XmlElement(name = "TotalScores")
    protected Integer totalScores;
    @XmlElement(name = "TotalHoles")
    protected Integer totalHoles;
    @XmlElement(name = "Hdcp")
    protected Integer hdcp;
    @XmlElement(name = "GrossEagles")
    protected Integer grossEagles;
    @XmlElement(name = "GrossBirdies")
    protected Integer grossBirdies;
    @XmlElement(name = "GrossPars")
    protected Integer grossPars;
    @XmlElement(name = "GrossBogies")
    protected Integer grossBogies;
    @XmlElement(name = "GrossOthers")
    protected Integer grossOthers;
    @XmlElement(name = "NetEagles")
    protected Integer netEagles;
    @XmlElement(name = "NetBirdies")
    protected Integer netBirdies;
    @XmlElement(name = "NetPars")
    protected Integer netPars;
    @XmlElement(name = "NetBogies")
    protected Integer netBogies;
    @XmlElement(name = "NetOthers")
    protected Integer netOthers;
    @XmlElement(name = "Remove")
    protected boolean remove;

    /**
     * Gets the value of the ctr property.
     * 
     */
    public int getCtr() {
        return ctr;
    }

    /**
     * Sets the value of the ctr property.
     * 
     */
    public void setCtr(int value) {
        this.ctr = value;
    }

    /**
     * Gets the value of the golfer property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getGolfer() {
        return golfer;
    }

    /**
     * Sets the value of the golfer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setGolfer(Integer value) {
        this.golfer = value;
    }

    /**
     * Gets the value of the year property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getYear() {
        return year;
    }

    /**
     * Sets the value of the year property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setYear(Integer value) {
        this.year = value;
    }

    /**
     * Gets the value of the totalScores property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTotalScores() {
        return totalScores;
    }

    /**
     * Sets the value of the totalScores property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTotalScores(Integer value) {
        this.totalScores = value;
    }

    /**
     * Gets the value of the totalHoles property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTotalHoles() {
        return totalHoles;
    }

    /**
     * Sets the value of the totalHoles property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTotalHoles(Integer value) {
        this.totalHoles = value;
    }

    /**
     * Gets the value of the hdcp property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getHdcp() {
        return hdcp;
    }

    /**
     * Sets the value of the hdcp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHdcp(Integer value) {
        this.hdcp = value;
    }

    /**
     * Gets the value of the grossEagles property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getGrossEagles() {
        return grossEagles;
    }

    /**
     * Sets the value of the grossEagles property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setGrossEagles(Integer value) {
        this.grossEagles = value;
    }

    /**
     * Gets the value of the grossBirdies property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getGrossBirdies() {
        return grossBirdies;
    }

    /**
     * Sets the value of the grossBirdies property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setGrossBirdies(Integer value) {
        this.grossBirdies = value;
    }

    /**
     * Gets the value of the grossPars property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getGrossPars() {
        return grossPars;
    }

    /**
     * Sets the value of the grossPars property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setGrossPars(Integer value) {
        this.grossPars = value;
    }

    /**
     * Gets the value of the grossBogies property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getGrossBogies() {
        return grossBogies;
    }

    /**
     * Sets the value of the grossBogies property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setGrossBogies(Integer value) {
        this.grossBogies = value;
    }

    /**
     * Gets the value of the grossOthers property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getGrossOthers() {
        return grossOthers;
    }

    /**
     * Sets the value of the grossOthers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setGrossOthers(Integer value) {
        this.grossOthers = value;
    }

    /**
     * Gets the value of the netEagles property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNetEagles() {
        return netEagles;
    }

    /**
     * Sets the value of the netEagles property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNetEagles(Integer value) {
        this.netEagles = value;
    }

    /**
     * Gets the value of the netBirdies property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNetBirdies() {
        return netBirdies;
    }

    /**
     * Sets the value of the netBirdies property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNetBirdies(Integer value) {
        this.netBirdies = value;
    }

    /**
     * Gets the value of the netPars property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNetPars() {
        return netPars;
    }

    /**
     * Sets the value of the netPars property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNetPars(Integer value) {
        this.netPars = value;
    }

    /**
     * Gets the value of the netBogies property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNetBogies() {
        return netBogies;
    }

    /**
     * Sets the value of the netBogies property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNetBogies(Integer value) {
        this.netBogies = value;
    }

    /**
     * Gets the value of the netOthers property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNetOthers() {
        return netOthers;
    }

    /**
     * Sets the value of the netOthers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNetOthers(Integer value) {
        this.netOthers = value;
    }

    /**
     * Gets the value of the remove property.
     * 
     */
    public boolean isRemove() {
        return remove;
    }

    /**
     * Sets the value of the remove property.
     * 
     */
    public void setRemove(boolean value) {
        this.remove = value;
    }

}
