//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.05 at 02:28:26 PM CDT 
//


package com.ejp.golf.league.legacy.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Week" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="WeekDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="EventType" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" minOccurs="0"/&gt;
 *         &lt;element name="Back9" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="Tees" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="50"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Back9Spcl" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="WeekBucket" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="Shotgun" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="Rebuild" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="Dateplayed" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "week",
    "weekDate",
    "eventType",
    "back9",
    "status",
    "tees",
    "back9Spcl",
    "weekBucket",
    "shotgun",
    "rebuild",
    "dateplayed"
})
@XmlRootElement(name = "WeekDates")
public class WeekDates {

    @XmlElement(name = "Week")
    protected Integer week;
    @XmlElement(name = "WeekDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar weekDate;
    @XmlElement(name = "EventType")
    @XmlSchemaType(name = "unsignedByte")
    protected Short eventType;
    @XmlElement(name = "Back9")
    protected boolean back9;
    @XmlElement(name = "Status")
    protected boolean status;
    @XmlElement(name = "Tees")
    protected String tees;
    @XmlElement(name = "Back9Spcl")
    protected boolean back9Spcl;
    @XmlElement(name = "WeekBucket")
    protected Integer weekBucket;
    @XmlElement(name = "Shotgun")
    protected boolean shotgun;
    @XmlElement(name = "Rebuild")
    protected boolean rebuild;
    @XmlElement(name = "Dateplayed")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateplayed;

    /**
     * Gets the value of the week property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getWeek() {
        return week;
    }

    /**
     * Sets the value of the week property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWeek(Integer value) {
        this.week = value;
    }

    /**
     * Gets the value of the weekDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getWeekDate() {
        return weekDate;
    }

    /**
     * Sets the value of the weekDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setWeekDate(XMLGregorianCalendar value) {
        this.weekDate = value;
    }

    /**
     * Gets the value of the eventType property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getEventType() {
        return eventType;
    }

    /**
     * Sets the value of the eventType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setEventType(Short value) {
        this.eventType = value;
    }

    /**
     * Gets the value of the back9 property.
     * 
     */
    public boolean isBack9() {
        return back9;
    }

    /**
     * Sets the value of the back9 property.
     * 
     */
    public void setBack9(boolean value) {
        this.back9 = value;
    }

    /**
     * Gets the value of the status property.
     * 
     */
    public boolean isStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     */
    public void setStatus(boolean value) {
        this.status = value;
    }

    /**
     * Gets the value of the tees property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTees() {
        return tees;
    }

    /**
     * Sets the value of the tees property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTees(String value) {
        this.tees = value;
    }

    /**
     * Gets the value of the back9Spcl property.
     * 
     */
    public boolean isBack9Spcl() {
        return back9Spcl;
    }

    /**
     * Sets the value of the back9Spcl property.
     * 
     */
    public void setBack9Spcl(boolean value) {
        this.back9Spcl = value;
    }

    /**
     * Gets the value of the weekBucket property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getWeekBucket() {
        return weekBucket;
    }

    /**
     * Sets the value of the weekBucket property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWeekBucket(Integer value) {
        this.weekBucket = value;
    }

    /**
     * Gets the value of the shotgun property.
     * 
     */
    public boolean isShotgun() {
        return shotgun;
    }

    /**
     * Sets the value of the shotgun property.
     * 
     */
    public void setShotgun(boolean value) {
        this.shotgun = value;
    }

    /**
     * Gets the value of the rebuild property.
     * 
     */
    public boolean isRebuild() {
        return rebuild;
    }

    /**
     * Sets the value of the rebuild property.
     * 
     */
    public void setRebuild(boolean value) {
        this.rebuild = value;
    }

    /**
     * Gets the value of the dateplayed property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateplayed() {
        return dateplayed;
    }

    /**
     * Sets the value of the dateplayed property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateplayed(XMLGregorianCalendar value) {
        this.dateplayed = value;
    }

}
